flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- cereal-0.5.2.0
- dbus-0.10.12
- fdo-notify-0.3.1
- libxml-sax-0.7.5
- lifted-base-0.2.3.6
- monad-control-1.0.1.0
- network-2.6.2.1
- parsec-3.1.11
- split-0.2.3.1
- suspend-0.2.0.0
- timers-0.2.0.3
- transformers-base-0.4.4
- xml-types-0.3.6
resolver: ghc-8.0.1
